# Book settings
title: reponame
author: UBI Center
logo: _static/ubi_center_logo_wide_blue.png

html:
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  google_analytics_id       : "UA-138885251-1"
  baseurl                   : "https://reponame.ubicenter.org"
  home_page_in_navbar       : true
  favicon                   : _static/favicon.png

repository:
  url: https://github.com/UBICenter/reponame
  path_to_book: jb

# This enables plotly's JavaScript
# See https://github.com/executablebooks/jupyter-book/issues/954#issuecomment-688220038
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
