name: Build and Deploy Jupyter Book
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: github.repository == 'UBICenter/reponame'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      # If you're using actions/checkout@v2 you must set persist-credentials to
      # false in most cases for the deployment to work correctly.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: reponame
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Build # Build Jupyter Book
        shell: bash -l {0}
        run: |
          cd jb
          jb build .
          touch _build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: jb/_build/html # The folder the action should deploy.
